import { db } from '@/db';
import { user, patients } from '@/db/schema';

async function main() {
    const baseDate = new Date('2024-01-01');
    
    const calculateBMI = (weight: number, height: number): number => {
        const heightInMeters = height / 100;
        return parseFloat((weight / (heightInMeters * heightInMeters)).toFixed(1));
    };

    const sampleUsers = [
        {
            id: 'user_patient_01',
            name: 'Mohamed Ali Hassan',
            email: 'mohamed.ali@gmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-08-15'),
            updatedAt: new Date('2023-08-15'),
        },
        {
            id: 'user_patient_02',
            name: 'Fatima Hassan Ibrahim',
            email: 'fatima.hassan@gmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-09-20'),
            updatedAt: new Date('2023-09-20'),
        },
        {
            id: 'user_patient_03',
            name: 'Ahmed Mahmoud Khalil',
            email: 'ahmed.mahmoud@yahoo.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-10-05'),
            updatedAt: new Date('2023-10-05'),
        },
        {
            id: 'user_patient_04',
            name: 'Amira Khalil Abdel Rahman',
            email: 'amira.khalil@hotmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-10-18'),
            updatedAt: new Date('2023-10-18'),
        },
        {
            id: 'user_patient_05',
            name: 'Omar Said Mohamed',
            email: 'omar.said@gmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-11-02'),
            updatedAt: new Date('2023-11-02'),
        },
        {
            id: 'user_patient_06',
            name: 'Nour El-Din Fathy',
            email: 'nour.eldin@gmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-11-15'),
            updatedAt: new Date('2023-11-15'),
        },
        {
            id: 'user_patient_07',
            name: 'Yasmin Ahmed Sayed',
            email: 'yasmin.ahmed@outlook.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-12-01'),
            updatedAt: new Date('2023-12-01'),
        },
        {
            id: 'user_patient_08',
            name: 'Karim Hassan Ali',
            email: 'karim.hassan@gmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2023-12-10'),
            updatedAt: new Date('2023-12-10'),
        },
        {
            id: 'user_patient_09',
            name: 'Mariam Khaled Mostafa',
            email: 'mariam.khaled@gmail.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-01-05'),
            updatedAt: new Date('2024-01-05'),
        },
        {
            id: 'user_patient_10',
            name: 'Youssef Ibrahim Farag',
            email: 'youssef.ibrahim@yahoo.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-01-20'),
            updatedAt: new Date('2024-01-20'),
        },
    ];

    await db.insert(user).values(sampleUsers);

    const samplePatients = [
        {
            userId: 'user_patient_01',
            nationalId: '29012154203817',
            fullName: 'Mohamed Ali Hassan',
            age: 35,
            gender: 'male',
            phone: '+201234567890',
            email: 'mohamed.ali@gmail.com',
            weightCurrent: 95.5,
            height: 178,
            bmi: calculateBMI(95.5, 178),
            bodyFatPercentage: 28.5,
            metabolismRate: 1850,
            medicalConditions: ['diabetes type 2'],
            allergies: [],
            emergencyContact: 'Wife - Noha Ali - +201234567891',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-08-15').toISOString(),
            updatedAt: new Date('2023-08-15').toISOString(),
        },
        {
            userId: 'user_patient_02',
            nationalId: '29092058901234',
            fullName: 'Fatima Hassan Ibrahim',
            age: 34,
            gender: 'female',
            phone: '+201123456789',
            email: 'fatima.hassan@gmail.com',
            weightCurrent: 82.0,
            height: 165,
            bmi: calculateBMI(82.0, 165),
            bodyFatPercentage: 32.0,
            metabolismRate: 1550,
            medicalConditions: ['PCOS', 'insulin resistance'],
            allergies: ['dairy'],
            emergencyContact: 'Husband - Hassan Ibrahim - +201123456788',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-09-20').toISOString(),
            updatedAt: new Date('2023-09-20').toISOString(),
        },
        {
            userId: 'user_patient_03',
            nationalId: '28410503205678',
            fullName: 'Ahmed Mahmoud Khalil',
            age: 40,
            gender: 'male',
            phone: '+201012345678',
            email: 'ahmed.mahmoud@yahoo.com',
            weightCurrent: 108.0,
            height: 182,
            bmi: calculateBMI(108.0, 182),
            bodyFatPercentage: 30.5,
            metabolismRate: 1920,
            medicalConditions: ['hypertension'],
            allergies: [],
            emergencyContact: 'Wife - Dina Khalil - +201012345679',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-10-05').toISOString(),
            updatedAt: new Date('2023-10-05').toISOString(),
        },
        {
            userId: 'user_patient_04',
            nationalId: '29303152301987',
            fullName: 'Amira Khalil Abdel Rahman',
            age: 31,
            gender: 'female',
            phone: '+201567890123',
            email: 'amira.khalil@hotmail.com',
            weightCurrent: 68.5,
            height: 170,
            bmi: calculateBMI(68.5, 170),
            bodyFatPercentage: 25.0,
            metabolismRate: 1650,
            medicalConditions: [],
            allergies: ['gluten'],
            emergencyContact: 'Mother - Hoda Khalil - +201567890124',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-10-18').toISOString(),
            updatedAt: new Date('2023-10-18').toISOString(),
        },
        {
            userId: 'user_patient_05',
            naturalId: '28106251504321',
            fullName: 'Omar Said Mohamed',
            age: 43,
            gender: 'male',
            phone: '+201098765432',
            email: 'omar.said@gmail.com',
            weightCurrent: 115.0,
            height: 185,
            bmi: calculateBMI(115.0, 185),
            bodyFatPercentage: 33.5,
            metabolismRate: 2050,
            medicalConditions: ['diabetes type 2', 'high cholesterol'],
            allergies: [],
            emergencyContact: 'Wife - Sara Mohamed - +201098765433',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-11-02').toISOString(),
            updatedAt: new Date('2023-11-02').toISOString(),
        },
        {
            userId: 'user_patient_06',
            nationalId: '29708153106789',
            fullName: 'Nour El-Din Fathy',
            age: 27,
            gender: 'male',
            phone: '+201234509876',
            email: 'nour.eldin@gmail.com',
            weightCurrent: 72.0,
            height: 175,
            bmi: calculateBMI(72.0, 175),
            bodyFatPercentage: 18.5,
            metabolismRate: 1780,
            medicalConditions: [],
            allergies: [],
            emergencyContact: 'Father - Fathy Nour - +201234509877',
            profilePhoto: null,
            status: 'inactive',
            createdAt: new Date('2023-11-15').toISOString(),
            updatedAt: new Date('2023-11-15').toISOString(),
        },
        {
            userId: 'user_patient_07',
            nationalId: '29605082801456',
            fullName: 'Yasmin Ahmed Sayed',
            age: 28,
            gender: 'female',
            phone: '+201156789012',
            email: 'yasmin.ahmed@outlook.com',
            weightCurrent: 75.0,
            height: 162,
            bmi: calculateBMI(75.0, 162),
            bodyFatPercentage: 28.0,
            metabolismRate: 1480,
            medicalConditions: ['thyroid disorder'],
            allergies: ['nuts'],
            emergencyContact: 'Sister - Salma Ahmed - +201156789013',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2023-12-01').toISOString(),
        },
        {
            userId: 'user_patient_08',
            nationalId: '28903122905432',
            fullName: 'Karim Hassan Ali',
            age: 35,
            gender: 'male',
            phone: '+201287654321',
            email: 'karim.hassan@gmail.com',
            weightCurrent: 88.5,
            height: 180,
            bmi: calculateBMI(88.5, 180),
            bodyFatPercentage: 24.5,
            metabolismRate: 1880,
            medicalConditions: [],
            allergies: [],
            emergencyContact: 'Wife - Layla Hassan - +201287654322',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2023-12-10').toISOString(),
            updatedAt: new Date('2023-12-10').toISOString(),
        },
        {
            userId: 'user_patient_09',
            nationalId: '29111183207654',
            fullName: 'Mariam Khaled Mostafa',
            age: 33,
            gender: 'female',
            phone: '+201045678901',
            email: 'mariam.khaled@gmail.com',
            weightCurrent: 92.0,
            height: 168,
            bmi: calculateBMI(92.0, 168),
            bodyFatPercentage: 35.0,
            metabolismRate: 1620,
            medicalConditions: ['PCOS'],
            allergies: ['dairy', 'gluten'],
            emergencyContact: 'Husband - Khaled Mostafa - +201045678902',
            profilePhoto: null,
            status: 'inactive',
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            userId: 'user_patient_10',
            nationalId: '28502093108765',
            fullName: 'Youssef Ibrahim Farag',
            age: 39,
            gender: 'male',
            phone: '+201198765432',
            email: 'youssef.ibrahim@yahoo.com',
            weightCurrent: 103.0,
            height: 177,
            bmi: calculateBMI(103.0, 177),
            bodyFatPercentage: 29.0,
            metabolismRate: 1950,
            medicalConditions: ['high cholesterol'],
            allergies: [],
            emergencyContact: 'Wife - Rana Farag - +201198765433',
            profilePhoto: null,
            status: 'active',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
    ];

    await db.insert(patients).values(samplePatients);
    
    console.log('✅ Patients seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});